# with no profile e.g. local dev, we're not on ec2, so we can't look up the region
---
spring:
  profiles: default

cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false

---
spring:
  profiles: dev

---
spring:
  profiles: prod

